Paths: 
    model: 'treatmentresponse/model/'

Data:
    data_path: '/home/d1304/no_backup/d1304/'
    train_val_split : 0.2                        # e.g. 0.2 -> 80% train, 20% validation
                                                # amount of patients for testing

Pretrained_Model:
    path :   # weights of a pretrained network

Training:
    batch_size : 8
    slice_size: [65,86]          # shape of input slice
    gpu_num : 6
    num_epochs : 150
    learning_rate: 0.001
    background_process : True
    num_parallel_calls: 4
    tensorboard: 0
    num_slice_per_group: 2    # number of slices taken from one sample as inputs

Case: 'train'
#can be 'train', 'test'
